

trigger:
- main

pool: pip_agent

stages:
  - stage: 
    displayName : "StaticCodeAnalysis"
    jobs:
      - job: Sonarqube
        displayName: "Sonar Qube"
        steps:
          - 
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'sonar -D sonar.host.url=http://localhost:9000 -D sonar.token=sqp_af3e9fc6955f19647f7115f1efe97d7b8f4f05c6 -D sonar.projectKey=pip_infra'
    workingDirectory: '$(Build.SourcesDirectory)/src'
